function calculateScore() {
    const attempted = parseFloat(document.getElementById('attempted').value) || 0;
    const wrong = parseFloat(document.getElementById('wrong').value) || 0;
    const ratio = parseFloat(document.getElementById('ratio').value) || 0;
    
    const correct = attempted - wrong;
    const penalty = ratio > 0 ? (wrong / ratio) : 0;
    const finalScore = correct - penalty;

    document.getElementById('score').innerText = finalScore.toFixed(2);
    return { attempted, wrong, correct, finalScore, ratio };
}

async function downloadPDF() {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    const data = calculateScore();
    
    const student = document.getElementById('studentName').value || "Guest User";
    const test = document.getElementById('testName').value || "General Assessment";
    const date = new Date().toLocaleString();

    // 1. Header & Branding
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text("eclipse7", 105, 20, { align: "center" }); // Center company name
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Official Performance Report", 105, 27, { align: "center" });

    // 2. Info Section
    doc.line(20, 35, 190, 35); 
    doc.text(`Student: ${student}`, 20, 45);
    doc.text(`Test Name: ${test}`, 20, 52);
    doc.text(`Date: ${date}`, 140, 45);
    doc.line(20, 58, 190, 58);

    // 3. Results Table
    doc.autoTable({
        startY: 65,
        theme: 'grid',
        headStyles: { fillColor: [40, 167, 69] },
        head: [['Metric', 'Value']],
        body: [
            ['Total Attempted', data.attempted],
            ['Correct Answers', data.correct],
            ['Wrong Answers', data.wrong],
            ['Marking Ratio', `1/${data.ratio}`],
            ['Final Score', data.finalScore.toFixed(2)]
        ],
    });

    // 4. Footer
    const finalY = doc.lastAutoTable.finalY + 20;
    doc.setFontSize(12);
    doc.text("Accuracy Analysis:", 20, finalY);
    const accuracy = ((data.correct / data.attempted) * 100 || 0).toFixed(1);
    doc.text(`${accuracy}% Accuracy Rate`, 20, finalY + 10);

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by eclipse7 Digital Solutions - https://eclipse7.odoo.com/", 105, 285, { align: "center" });

    // Save File
    doc.save(`${student}_${test}_Report.pdf`);
}
